gateways:
  default:
    port: 6021
ui:
  gateways: default
mcp:
  gateways: default
  targets:
    - name: weather
      mcp:
        host: http://localhost:8080/mcp
  sessionMode: stateful
  prefixPolicy: always
  failurePolicy: failOpen
