apiVersion: v1
kind: ServiceAccount
metadata:
  name: transit-controller
  namespace: transit-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transit-controller
rules:
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses, gateways, httproutes, referencegrants]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses/status, gateways/status, httproutes/status, gateways/finalizers]
    verbs: [update, patch]
  - apiGroups: [networking.dubbo.apache.org]
    resources: [transitservices]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [namespaces, secrets]
    verbs: [get, list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services, serviceaccounts, configmaps]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: transit-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: transit-controller
subjects:
  - kind: ServiceAccount
    name: transit-controller
    namespace: transit-system
