// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v6.33.0
// source: route/v1/agent_config.proto

package routev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentProviderKind int32

const (
	AgentProviderKind_AGENT_PROVIDER_KIND_UNSPECIFIED AgentProviderKind = 0
	AgentProviderKind_OPENAI                          AgentProviderKind = 1
	AgentProviderKind_ANTHROPIC                       AgentProviderKind = 2
)

// Enum value maps for AgentProviderKind.
var (
	AgentProviderKind_name = map[int32]string{
		0: "AGENT_PROVIDER_KIND_UNSPECIFIED",
		1: "OPENAI",
		2: "ANTHROPIC",
	}
	AgentProviderKind_value = map[string]int32{
		"AGENT_PROVIDER_KIND_UNSPECIFIED": 0,
		"OPENAI":                          1,
		"ANTHROPIC":                       2,
	}
)

func (x AgentProviderKind) Enum() *AgentProviderKind {
	p := new(AgentProviderKind)
	*p = x
	return p
}

func (x AgentProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_route_v1_agent_config_proto_enumTypes[0].Descriptor()
}

func (AgentProviderKind) Type() protoreflect.EnumType {
	return &file_route_v1_agent_config_proto_enumTypes[0]
}

func (x AgentProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentProviderKind.Descriptor instead.
func (AgentProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{0}
}

type AgentProtocol int32

const (
	AgentProtocol_AGENT_PROTOCOL_UNSPECIFIED AgentProtocol = 0
	AgentProtocol_HTTP                       AgentProtocol = 1
	AgentProtocol_LLM                        AgentProtocol = 2
	AgentProtocol_MCP                        AgentProtocol = 3
	AgentProtocol_A2A                        AgentProtocol = 4
)

// Enum value maps for AgentProtocol.
var (
	AgentProtocol_name = map[int32]string{
		0: "AGENT_PROTOCOL_UNSPECIFIED",
		1: "HTTP",
		2: "LLM",
		3: "MCP",
		4: "A2A",
	}
	AgentProtocol_value = map[string]int32{
		"AGENT_PROTOCOL_UNSPECIFIED": 0,
		"HTTP":                       1,
		"LLM":                        2,
		"MCP":                        3,
		"A2A":                        4,
	}
)

func (x AgentProtocol) Enum() *AgentProtocol {
	p := new(AgentProtocol)
	*p = x
	return p
}

func (x AgentProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_route_v1_agent_config_proto_enumTypes[1].Descriptor()
}

func (AgentProtocol) Type() protoreflect.EnumType {
	return &file_route_v1_agent_config_proto_enumTypes[1]
}

func (x AgentProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentProtocol.Descriptor instead.
func (AgentProtocol) EnumDescriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{1}
}

type AgentRateLimitKey int32

const (
	AgentRateLimitKey_AGENT_RATE_LIMIT_KEY_UNSPECIFIED AgentRateLimitKey = 0
	AgentRateLimitKey_ROUTE                            AgentRateLimitKey = 1
	AgentRateLimitKey_BACKEND                          AgentRateLimitKey = 2
	AgentRateLimitKey_HEADER                           AgentRateLimitKey = 3
)

// Enum value maps for AgentRateLimitKey.
var (
	AgentRateLimitKey_name = map[int32]string{
		0: "AGENT_RATE_LIMIT_KEY_UNSPECIFIED",
		1: "ROUTE",
		2: "BACKEND",
		3: "HEADER",
	}
	AgentRateLimitKey_value = map[string]int32{
		"AGENT_RATE_LIMIT_KEY_UNSPECIFIED": 0,
		"ROUTE":                            1,
		"BACKEND":                          2,
		"HEADER":                           3,
	}
)

func (x AgentRateLimitKey) Enum() *AgentRateLimitKey {
	p := new(AgentRateLimitKey)
	*p = x
	return p
}

func (x AgentRateLimitKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRateLimitKey) Descriptor() protoreflect.EnumDescriptor {
	return file_route_v1_agent_config_proto_enumTypes[2].Descriptor()
}

func (AgentRateLimitKey) Type() protoreflect.EnumType {
	return &file_route_v1_agent_config_proto_enumTypes[2]
}

func (x AgentRateLimitKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRateLimitKey.Descriptor instead.
func (AgentRateLimitKey) EnumDescriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{2}
}

// AgentConfig is the mesh-native LLM, MCP, and A2A slice compiled by dubbod
// from TransitService and HTTPRoute resources.
type AgentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*AgentProvider       `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	Backends      []*AgentBackend        `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	AgentRoutes   []*AgentRoute          `protobuf:"bytes,3,rep,name=agent_routes,json=agentRoutes,proto3" json:"agent_routes,omitempty"`
	Policies      []*AgentPolicy         `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_route_v1_agent_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfig) GetProviders() []*AgentProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *AgentConfig) GetBackends() []*AgentBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *AgentConfig) GetAgentRoutes() []*AgentRoute {
	if x != nil {
		return x.AgentRoutes
	}
	return nil
}

func (x *AgentConfig) GetPolicies() []*AgentPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type AgentProvider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind           AgentProviderKind      `protobuf:"varint,2,opt,name=kind,proto3,enum=route.v1.AgentProviderKind" json:"kind,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Credential     *SecretKeyReference    `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	RequestHeaders []*AgentHeaderValue    `protobuf:"bytes,5,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentProvider) Reset() {
	*x = AgentProvider{}
	mi := &file_route_v1_agent_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProvider) ProtoMessage() {}

func (x *AgentProvider) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProvider.ProtoReflect.Descriptor instead.
func (*AgentProvider) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{1}
}

func (x *AgentProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentProvider) GetKind() AgentProviderKind {
	if x != nil {
		return x.Kind
	}
	return AgentProviderKind_AGENT_PROVIDER_KIND_UNSPECIFIED
}

func (x *AgentProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AgentProvider) GetCredential() *SecretKeyReference {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AgentProvider) GetRequestHeaders() []*AgentHeaderValue {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

type AgentBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Backend:
	//
	//	*AgentBackend_Http
	//	*AgentBackend_Llm
	//	*AgentBackend_Mcp
	//	*AgentBackend_A2A
	Backend       isAgentBackend_Backend `protobuf_oneof:"backend"`
	Policies      []string               `protobuf:"bytes,6,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBackend) Reset() {
	*x = AgentBackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBackend) ProtoMessage() {}

func (x *AgentBackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBackend.ProtoReflect.Descriptor instead.
func (*AgentBackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{2}
}

func (x *AgentBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentBackend) GetBackend() isAgentBackend_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *AgentBackend) GetHttp() *HTTPBackend {
	if x != nil {
		if x, ok := x.Backend.(*AgentBackend_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *AgentBackend) GetLlm() *LLMBackend {
	if x != nil {
		if x, ok := x.Backend.(*AgentBackend_Llm); ok {
			return x.Llm
		}
	}
	return nil
}

func (x *AgentBackend) GetMcp() *MCPBackend {
	if x != nil {
		if x, ok := x.Backend.(*AgentBackend_Mcp); ok {
			return x.Mcp
		}
	}
	return nil
}

func (x *AgentBackend) GetA2A() *A2ABackend {
	if x != nil {
		if x, ok := x.Backend.(*AgentBackend_A2A); ok {
			return x.A2A
		}
	}
	return nil
}

func (x *AgentBackend) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

type isAgentBackend_Backend interface {
	isAgentBackend_Backend()
}

type AgentBackend_Http struct {
	Http *HTTPBackend `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type AgentBackend_Llm struct {
	Llm *LLMBackend `protobuf:"bytes,3,opt,name=llm,proto3,oneof"`
}

type AgentBackend_Mcp struct {
	Mcp *MCPBackend `protobuf:"bytes,4,opt,name=mcp,proto3,oneof"`
}

type AgentBackend_A2A struct {
	A2A *A2ABackend `protobuf:"bytes,5,opt,name=a2a,proto3,oneof"`
}

func (*AgentBackend_Http) isAgentBackend_Backend() {}

func (*AgentBackend_Llm) isAgentBackend_Backend() {}

func (*AgentBackend_Mcp) isAgentBackend_Backend() {}

func (*AgentBackend_A2A) isAgentBackend_Backend() {}

type HTTPBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPBackend) Reset() {
	*x = HTTPBackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPBackend) ProtoMessage() {}

func (x *HTTPBackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPBackend.ProtoReflect.Descriptor instead.
func (*HTTPBackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPBackend) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type LLMBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Models        []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ModelRewrites map[string]string      `protobuf:"bytes,4,rep,name=model_rewrites,json=modelRewrites,proto3" json:"model_rewrites,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMBackend) Reset() {
	*x = LLMBackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMBackend) ProtoMessage() {}

func (x *LLMBackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMBackend.ProtoReflect.Descriptor instead.
func (*LLMBackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{4}
}

func (x *LLMBackend) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMBackend) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *LLMBackend) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LLMBackend) GetModelRewrites() map[string]string {
	if x != nil {
		return x.ModelRewrites
	}
	return nil
}

type MCPBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tools         []string               `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPBackend) Reset() {
	*x = MCPBackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPBackend) ProtoMessage() {}

func (x *MCPBackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPBackend.ProtoReflect.Descriptor instead.
func (*MCPBackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{5}
}

func (x *MCPBackend) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MCPBackend) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type A2ABackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A2ABackend) Reset() {
	*x = A2ABackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A2ABackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A2ABackend) ProtoMessage() {}

func (x *A2ABackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A2ABackend.ProtoReflect.Descriptor instead.
func (*A2ABackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{6}
}

func (x *A2ABackend) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *A2ABackend) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type AgentRoute struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol         AgentProtocol          `protobuf:"varint,2,opt,name=protocol,proto3,enum=route.v1.AgentProtocol" json:"protocol,omitempty"`
	Matches          []*AgentRouteMatch     `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
	WeightedBackends []*WeightedBackend     `protobuf:"bytes,4,rep,name=weighted_backends,json=weightedBackends,proto3" json:"weighted_backends,omitempty"`
	Policies         []string               `protobuf:"bytes,5,rep,name=policies,proto3" json:"policies,omitempty"`
	Rewrite          *PathRewrite           `protobuf:"bytes,6,opt,name=rewrite,proto3" json:"rewrite,omitempty"`
	// Empty preserves the legacy all-listeners behavior used by dubbod.
	ListenerPorts []uint32 `protobuf:"varint,7,rep,packed,name=listener_ports,json=listenerPorts,proto3" json:"listener_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRoute) Reset() {
	*x = AgentRoute{}
	mi := &file_route_v1_agent_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRoute) ProtoMessage() {}

func (x *AgentRoute) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRoute.ProtoReflect.Descriptor instead.
func (*AgentRoute) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{7}
}

func (x *AgentRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRoute) GetProtocol() AgentProtocol {
	if x != nil {
		return x.Protocol
	}
	return AgentProtocol_AGENT_PROTOCOL_UNSPECIFIED
}

func (x *AgentRoute) GetMatches() []*AgentRouteMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *AgentRoute) GetWeightedBackends() []*WeightedBackend {
	if x != nil {
		return x.WeightedBackends
	}
	return nil
}

func (x *AgentRoute) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *AgentRoute) GetRewrite() *PathRewrite {
	if x != nil {
		return x.Rewrite
	}
	return nil
}

func (x *AgentRoute) GetListenerPorts() []uint32 {
	if x != nil {
		return x.ListenerPorts
	}
	return nil
}

type AgentRouteMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *AgentPathMatch        `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Tool          string                 `protobuf:"bytes,5,opt,name=tool,proto3" json:"tool,omitempty"`
	Agent         string                 `protobuf:"bytes,6,opt,name=agent,proto3" json:"agent,omitempty"`
	Headers       []*AgentHeaderMatch    `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRouteMatch) Reset() {
	*x = AgentRouteMatch{}
	mi := &file_route_v1_agent_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRouteMatch) ProtoMessage() {}

func (x *AgentRouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRouteMatch.ProtoReflect.Descriptor instead.
func (*AgentRouteMatch) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{8}
}

func (x *AgentRouteMatch) GetPath() *AgentPathMatch {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *AgentRouteMatch) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AgentRouteMatch) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AgentRouteMatch) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRouteMatch) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *AgentRouteMatch) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *AgentRouteMatch) GetHeaders() []*AgentHeaderMatch {
	if x != nil {
		return x.Headers
	}
	return nil
}

type AgentPathMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Match:
	//
	//	*AgentPathMatch_Prefix
	//	*AgentPathMatch_Exact
	Match         isAgentPathMatch_Match `protobuf_oneof:"match"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPathMatch) Reset() {
	*x = AgentPathMatch{}
	mi := &file_route_v1_agent_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPathMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPathMatch) ProtoMessage() {}

func (x *AgentPathMatch) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPathMatch.ProtoReflect.Descriptor instead.
func (*AgentPathMatch) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{9}
}

func (x *AgentPathMatch) GetMatch() isAgentPathMatch_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *AgentPathMatch) GetPrefix() string {
	if x != nil {
		if x, ok := x.Match.(*AgentPathMatch_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *AgentPathMatch) GetExact() string {
	if x != nil {
		if x, ok := x.Match.(*AgentPathMatch_Exact); ok {
			return x.Exact
		}
	}
	return ""
}

type isAgentPathMatch_Match interface {
	isAgentPathMatch_Match()
}

type AgentPathMatch_Prefix struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3,oneof"`
}

type AgentPathMatch_Exact struct {
	Exact string `protobuf:"bytes,2,opt,name=exact,proto3,oneof"`
}

func (*AgentPathMatch_Prefix) isAgentPathMatch_Match() {}

func (*AgentPathMatch_Exact) isAgentPathMatch_Match() {}

type AgentHeaderMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeaderMatch) Reset() {
	*x = AgentHeaderMatch{}
	mi := &file_route_v1_agent_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeaderMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeaderMatch) ProtoMessage() {}

func (x *AgentHeaderMatch) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeaderMatch.ProtoReflect.Descriptor instead.
func (*AgentHeaderMatch) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{10}
}

func (x *AgentHeaderMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentHeaderMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WeightedBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightedBackend) Reset() {
	*x = WeightedBackend{}
	mi := &file_route_v1_agent_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedBackend) ProtoMessage() {}

func (x *WeightedBackend) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedBackend.ProtoReflect.Descriptor instead.
func (*WeightedBackend) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{11}
}

func (x *WeightedBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeightedBackend) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PathRewrite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway API URLRewrite ReplacePrefixMatch value.
	ReplacePrefixMatch string `protobuf:"bytes,1,opt,name=replace_prefix_match,json=replacePrefixMatch,proto3" json:"replace_prefix_match,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PathRewrite) Reset() {
	*x = PathRewrite{}
	mi := &file_route_v1_agent_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRewrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRewrite) ProtoMessage() {}

func (x *PathRewrite) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRewrite.ProtoReflect.Descriptor instead.
func (*PathRewrite) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{12}
}

func (x *PathRewrite) GetReplacePrefixMatch() string {
	if x != nil {
		return x.ReplacePrefixMatch
	}
	return ""
}

type AgentPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Auth            *ClientAuthPolicy      `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	RateLimit       *AgentRateLimitPolicy  `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	TokenLimit      *AgentTokenLimitPolicy `protobuf:"bytes,4,opt,name=token_limit,json=tokenLimit,proto3" json:"token_limit,omitempty"`
	Timeout         *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retry           *AgentRetryPolicy      `protobuf:"bytes,6,opt,name=retry,proto3" json:"retry,omitempty"`
	MaxBodyBytes    uint64                 `protobuf:"varint,7,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	RequestHeaders  *AgentHeaderTransform  `protobuf:"bytes,8,opt,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	ResponseHeaders *AgentHeaderTransform  `protobuf:"bytes,9,opt,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentPolicy) Reset() {
	*x = AgentPolicy{}
	mi := &file_route_v1_agent_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPolicy) ProtoMessage() {}

func (x *AgentPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPolicy.ProtoReflect.Descriptor instead.
func (*AgentPolicy) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{13}
}

func (x *AgentPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentPolicy) GetAuth() *ClientAuthPolicy {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *AgentPolicy) GetRateLimit() *AgentRateLimitPolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *AgentPolicy) GetTokenLimit() *AgentTokenLimitPolicy {
	if x != nil {
		return x.TokenLimit
	}
	return nil
}

func (x *AgentPolicy) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *AgentPolicy) GetRetry() *AgentRetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *AgentPolicy) GetMaxBodyBytes() uint64 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

func (x *AgentPolicy) GetRequestHeaders() *AgentHeaderTransform {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *AgentPolicy) GetResponseHeaders() *AgentHeaderTransform {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

type ClientAuthPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SecretRef     *SecretKeyReference    `protobuf:"bytes,2,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthPolicy) Reset() {
	*x = ClientAuthPolicy{}
	mi := &file_route_v1_agent_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthPolicy) ProtoMessage() {}

func (x *ClientAuthPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthPolicy.ProtoReflect.Descriptor instead.
func (*ClientAuthPolicy) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{14}
}

func (x *ClientAuthPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ClientAuthPolicy) GetSecretRef() *SecretKeyReference {
	if x != nil {
		return x.SecretRef
	}
	return nil
}

type SecretKeyReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeyReference) Reset() {
	*x = SecretKeyReference{}
	mi := &file_route_v1_agent_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeyReference) ProtoMessage() {}

func (x *SecretKeyReference) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeyReference.ProtoReflect.Descriptor instead.
func (*SecretKeyReference) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{15}
}

func (x *SecretKeyReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretKeyReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretKeyReference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AgentRateLimitPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      uint32                 `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Key           AgentRateLimitKey      `protobuf:"varint,3,opt,name=key,proto3,enum=route.v1.AgentRateLimitKey" json:"key,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRateLimitPolicy) Reset() {
	*x = AgentRateLimitPolicy{}
	mi := &file_route_v1_agent_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRateLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRateLimitPolicy) ProtoMessage() {}

func (x *AgentRateLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRateLimitPolicy.ProtoReflect.Descriptor instead.
func (*AgentRateLimitPolicy) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{16}
}

func (x *AgentRateLimitPolicy) GetRequests() uint32 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *AgentRateLimitPolicy) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *AgentRateLimitPolicy) GetKey() AgentRateLimitKey {
	if x != nil {
		return x.Key
	}
	return AgentRateLimitKey_AGENT_RATE_LIMIT_KEY_UNSPECIFIED
}

func (x *AgentRateLimitPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type AgentTokenLimitPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        uint64                 `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	Key           AgentRateLimitKey      `protobuf:"varint,3,opt,name=key,proto3,enum=route.v1.AgentRateLimitKey" json:"key,omitempty"`
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTokenLimitPolicy) Reset() {
	*x = AgentTokenLimitPolicy{}
	mi := &file_route_v1_agent_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTokenLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTokenLimitPolicy) ProtoMessage() {}

func (x *AgentTokenLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTokenLimitPolicy.ProtoReflect.Descriptor instead.
func (*AgentTokenLimitPolicy) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{17}
}

func (x *AgentTokenLimitPolicy) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *AgentTokenLimitPolicy) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *AgentTokenLimitPolicy) GetKey() AgentRateLimitKey {
	if x != nil {
		return x.Key
	}
	return AgentRateLimitKey_AGENT_RATE_LIMIT_KEY_UNSPECIFIED
}

func (x *AgentTokenLimitPolicy) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type AgentRetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      uint32                 `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	StatusCodes   []uint32               `protobuf:"varint,2,rep,packed,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRetryPolicy) Reset() {
	*x = AgentRetryPolicy{}
	mi := &file_route_v1_agent_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRetryPolicy) ProtoMessage() {}

func (x *AgentRetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRetryPolicy.ProtoReflect.Descriptor instead.
func (*AgentRetryPolicy) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{18}
}

func (x *AgentRetryPolicy) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *AgentRetryPolicy) GetStatusCodes() []uint32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type AgentHeaderTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Add           []*AgentHeaderValue    `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeaderTransform) Reset() {
	*x = AgentHeaderTransform{}
	mi := &file_route_v1_agent_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeaderTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeaderTransform) ProtoMessage() {}

func (x *AgentHeaderTransform) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeaderTransform.ProtoReflect.Descriptor instead.
func (*AgentHeaderTransform) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{19}
}

func (x *AgentHeaderTransform) GetAdd() []*AgentHeaderValue {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *AgentHeaderTransform) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type AgentHeaderValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeaderValue) Reset() {
	*x = AgentHeaderValue{}
	mi := &file_route_v1_agent_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeaderValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeaderValue) ProtoMessage() {}

func (x *AgentHeaderValue) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_agent_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeaderValue.ProtoReflect.Descriptor instead.
func (*AgentHeaderValue) Descriptor() ([]byte, []int) {
	return file_route_v1_agent_config_proto_rawDescGZIP(), []int{20}
}

func (x *AgentHeaderValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentHeaderValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_route_v1_agent_config_proto protoreflect.FileDescriptor

const file_route_v1_agent_config_proto_rawDesc = "" +
	"\n" +
	"\x1broute/v1/agent_config.proto\x12\broute.v1\x1a\x1egoogle/protobuf/duration.proto\"\xe4\x01\n" +
	"\vAgentConfig\x125\n" +
	"\tproviders\x18\x01 \x03(\v2\x17.route.v1.AgentProviderR\tproviders\x122\n" +
	"\bbackends\x18\x02 \x03(\v2\x16.route.v1.AgentBackendR\bbackends\x127\n" +
	"\fagent_routes\x18\x03 \x03(\v2\x14.route.v1.AgentRouteR\vagentRoutes\x121\n" +
	"\bpolicies\x18\x04 \x03(\v2\x15.route.v1.AgentPolicyR\bpolicies\"\xf2\x01\n" +
	"\rAgentProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.route.v1.AgentProviderKindR\x04kind\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12<\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2\x1c.route.v1.SecretKeyReferenceR\n" +
	"credential\x12C\n" +
	"\x0frequest_headers\x18\x05 \x03(\v2\x1a.route.v1.AgentHeaderValueR\x0erequestHeaders\"\xf4\x01\n" +
	"\fAgentBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04http\x18\x02 \x01(\v2\x15.route.v1.HTTPBackendH\x00R\x04http\x12(\n" +
	"\x03llm\x18\x03 \x01(\v2\x14.route.v1.LLMBackendH\x00R\x03llm\x12(\n" +
	"\x03mcp\x18\x04 \x01(\v2\x14.route.v1.MCPBackendH\x00R\x03mcp\x12(\n" +
	"\x03a2a\x18\x05 \x01(\v2\x14.route.v1.A2ABackendH\x00R\x03a2a\x12\x1a\n" +
	"\bpolicies\x18\x06 \x03(\tR\bpoliciesB\t\n" +
	"\abackend\")\n" +
	"\vHTTPBackend\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"\xee\x01\n" +
	"\n" +
	"LLMBackend\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12N\n" +
	"\x0emodel_rewrites\x18\x04 \x03(\v2'.route.v1.LLMBackend.ModelRewritesEntryR\rmodelRewrites\x1a@\n" +
	"\x12ModelRewritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\n" +
	"MCPBackend\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05tools\x18\x02 \x03(\tR\x05tools\">\n" +
	"\n" +
	"A2ABackend\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\"\xc6\x02\n" +
	"\n" +
	"AgentRoute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x17.route.v1.AgentProtocolR\bprotocol\x123\n" +
	"\amatches\x18\x03 \x03(\v2\x19.route.v1.AgentRouteMatchR\amatches\x12F\n" +
	"\x11weighted_backends\x18\x04 \x03(\v2\x19.route.v1.WeightedBackendR\x10weightedBackends\x12\x1a\n" +
	"\bpolicies\x18\x05 \x03(\tR\bpolicies\x12/\n" +
	"\arewrite\x18\x06 \x01(\v2\x15.route.v1.PathRewriteR\arewrite\x12%\n" +
	"\x0elistener_ports\x18\a \x03(\rR\rlistenerPorts\"\xe1\x01\n" +
	"\x0fAgentRouteMatch\x12,\n" +
	"\x04path\x18\x01 \x01(\v2\x18.route.v1.AgentPathMatchR\x04path\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04tool\x18\x05 \x01(\tR\x04tool\x12\x14\n" +
	"\x05agent\x18\x06 \x01(\tR\x05agent\x124\n" +
	"\aheaders\x18\a \x03(\v2\x1a.route.v1.AgentHeaderMatchR\aheaders\"K\n" +
	"\x0eAgentPathMatch\x12\x18\n" +
	"\x06prefix\x18\x01 \x01(\tH\x00R\x06prefix\x12\x16\n" +
	"\x05exact\x18\x02 \x01(\tH\x00R\x05exactB\a\n" +
	"\x05match\"<\n" +
	"\x10AgentHeaderMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\x0fWeightedBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\"?\n" +
	"\vPathRewrite\x120\n" +
	"\x14replace_prefix_match\x18\x01 \x01(\tR\x12replacePrefixMatch\"\xf3\x03\n" +
	"\vAgentPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04auth\x18\x02 \x01(\v2\x1a.route.v1.ClientAuthPolicyR\x04auth\x12=\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\v2\x1e.route.v1.AgentRateLimitPolicyR\trateLimit\x12@\n" +
	"\vtoken_limit\x18\x04 \x01(\v2\x1f.route.v1.AgentTokenLimitPolicyR\n" +
	"tokenLimit\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x120\n" +
	"\x05retry\x18\x06 \x01(\v2\x1a.route.v1.AgentRetryPolicyR\x05retry\x12$\n" +
	"\x0emax_body_bytes\x18\a \x01(\x04R\fmaxBodyBytes\x12G\n" +
	"\x0frequest_headers\x18\b \x01(\v2\x1e.route.v1.AgentHeaderTransformR\x0erequestHeaders\x12I\n" +
	"\x10response_headers\x18\t \x01(\v2\x1e.route.v1.AgentHeaderTransformR\x0fresponseHeaders\"g\n" +
	"\x10ClientAuthPolicy\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12;\n" +
	"\n" +
	"secret_ref\x18\x02 \x01(\v2\x1c.route.v1.SecretKeyReferenceR\tsecretRef\"X\n" +
	"\x12SecretKeyReference\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\xac\x01\n" +
	"\x14AgentRateLimitPolicy\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\rR\brequests\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12-\n" +
	"\x03key\x18\x03 \x01(\x0e2\x1b.route.v1.AgentRateLimitKeyR\x03key\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\"\xa9\x01\n" +
	"\x15AgentTokenLimitPolicy\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x04R\x06tokens\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12-\n" +
	"\x03key\x18\x03 \x01(\x0e2\x1b.route.v1.AgentRateLimitKeyR\x03key\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\"Q\n" +
	"\x10AgentRetryPolicy\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\rR\battempts\x12!\n" +
	"\fstatus_codes\x18\x02 \x03(\rR\vstatusCodes\"\\\n" +
	"\x14AgentHeaderTransform\x12,\n" +
	"\x03add\x18\x01 \x03(\v2\x1a.route.v1.AgentHeaderValueR\x03add\x12\x16\n" +
	"\x06remove\x18\x02 \x03(\tR\x06remove\"<\n" +
	"\x10AgentHeaderValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*S\n" +
	"\x11AgentProviderKind\x12#\n" +
	"\x1fAGENT_PROVIDER_KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OPENAI\x10\x01\x12\r\n" +
	"\tANTHROPIC\x10\x02*T\n" +
	"\rAgentProtocol\x12\x1e\n" +
	"\x1aAGENT_PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\a\n" +
	"\x03LLM\x10\x02\x12\a\n" +
	"\x03MCP\x10\x03\x12\a\n" +
	"\x03A2A\x10\x04*]\n" +
	"\x11AgentRateLimitKey\x12$\n" +
	" AGENT_RATE_LIMIT_KEY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ROUTE\x10\x01\x12\v\n" +
	"\aBACKEND\x10\x02\x12\n" +
	"\n" +
	"\x06HEADER\x10\x03B+Z)github.com/dubml/xds-api/route/v1;routev1b\x06proto3"

var (
	file_route_v1_agent_config_proto_rawDescOnce sync.Once
	file_route_v1_agent_config_proto_rawDescData []byte
)

func file_route_v1_agent_config_proto_rawDescGZIP() []byte {
	file_route_v1_agent_config_proto_rawDescOnce.Do(func() {
		file_route_v1_agent_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_v1_agent_config_proto_rawDesc), len(file_route_v1_agent_config_proto_rawDesc)))
	})
	return file_route_v1_agent_config_proto_rawDescData
}

var file_route_v1_agent_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_route_v1_agent_config_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_route_v1_agent_config_proto_goTypes = []any{
	(AgentProviderKind)(0),        // 0: route.v1.AgentProviderKind
	(AgentProtocol)(0),            // 1: route.v1.AgentProtocol
	(AgentRateLimitKey)(0),        // 2: route.v1.AgentRateLimitKey
	(*AgentConfig)(nil),           // 3: route.v1.AgentConfig
	(*AgentProvider)(nil),         // 4: route.v1.AgentProvider
	(*AgentBackend)(nil),          // 5: route.v1.AgentBackend
	(*HTTPBackend)(nil),           // 6: route.v1.HTTPBackend
	(*LLMBackend)(nil),            // 7: route.v1.LLMBackend
	(*MCPBackend)(nil),            // 8: route.v1.MCPBackend
	(*A2ABackend)(nil),            // 9: route.v1.A2ABackend
	(*AgentRoute)(nil),            // 10: route.v1.AgentRoute
	(*AgentRouteMatch)(nil),       // 11: route.v1.AgentRouteMatch
	(*AgentPathMatch)(nil),        // 12: route.v1.AgentPathMatch
	(*AgentHeaderMatch)(nil),      // 13: route.v1.AgentHeaderMatch
	(*WeightedBackend)(nil),       // 14: route.v1.WeightedBackend
	(*PathRewrite)(nil),           // 15: route.v1.PathRewrite
	(*AgentPolicy)(nil),           // 16: route.v1.AgentPolicy
	(*ClientAuthPolicy)(nil),      // 17: route.v1.ClientAuthPolicy
	(*SecretKeyReference)(nil),    // 18: route.v1.SecretKeyReference
	(*AgentRateLimitPolicy)(nil),  // 19: route.v1.AgentRateLimitPolicy
	(*AgentTokenLimitPolicy)(nil), // 20: route.v1.AgentTokenLimitPolicy
	(*AgentRetryPolicy)(nil),      // 21: route.v1.AgentRetryPolicy
	(*AgentHeaderTransform)(nil),  // 22: route.v1.AgentHeaderTransform
	(*AgentHeaderValue)(nil),      // 23: route.v1.AgentHeaderValue
	nil,                           // 24: route.v1.LLMBackend.ModelRewritesEntry
	(*durationpb.Duration)(nil),   // 25: google.protobuf.Duration
}
var file_route_v1_agent_config_proto_depIdxs = []int32{
	4,  // 0: route.v1.AgentConfig.providers:type_name -> route.v1.AgentProvider
	5,  // 1: route.v1.AgentConfig.backends:type_name -> route.v1.AgentBackend
	10, // 2: route.v1.AgentConfig.agent_routes:type_name -> route.v1.AgentRoute
	16, // 3: route.v1.AgentConfig.policies:type_name -> route.v1.AgentPolicy
	0,  // 4: route.v1.AgentProvider.kind:type_name -> route.v1.AgentProviderKind
	18, // 5: route.v1.AgentProvider.credential:type_name -> route.v1.SecretKeyReference
	23, // 6: route.v1.AgentProvider.request_headers:type_name -> route.v1.AgentHeaderValue
	6,  // 7: route.v1.AgentBackend.http:type_name -> route.v1.HTTPBackend
	7,  // 8: route.v1.AgentBackend.llm:type_name -> route.v1.LLMBackend
	8,  // 9: route.v1.AgentBackend.mcp:type_name -> route.v1.MCPBackend
	9,  // 10: route.v1.AgentBackend.a2a:type_name -> route.v1.A2ABackend
	24, // 11: route.v1.LLMBackend.model_rewrites:type_name -> route.v1.LLMBackend.ModelRewritesEntry
	1,  // 12: route.v1.AgentRoute.protocol:type_name -> route.v1.AgentProtocol
	11, // 13: route.v1.AgentRoute.matches:type_name -> route.v1.AgentRouteMatch
	14, // 14: route.v1.AgentRoute.weighted_backends:type_name -> route.v1.WeightedBackend
	15, // 15: route.v1.AgentRoute.rewrite:type_name -> route.v1.PathRewrite
	12, // 16: route.v1.AgentRouteMatch.path:type_name -> route.v1.AgentPathMatch
	13, // 17: route.v1.AgentRouteMatch.headers:type_name -> route.v1.AgentHeaderMatch
	17, // 18: route.v1.AgentPolicy.auth:type_name -> route.v1.ClientAuthPolicy
	19, // 19: route.v1.AgentPolicy.rate_limit:type_name -> route.v1.AgentRateLimitPolicy
	20, // 20: route.v1.AgentPolicy.token_limit:type_name -> route.v1.AgentTokenLimitPolicy
	25, // 21: route.v1.AgentPolicy.timeout:type_name -> google.protobuf.Duration
	21, // 22: route.v1.AgentPolicy.retry:type_name -> route.v1.AgentRetryPolicy
	22, // 23: route.v1.AgentPolicy.request_headers:type_name -> route.v1.AgentHeaderTransform
	22, // 24: route.v1.AgentPolicy.response_headers:type_name -> route.v1.AgentHeaderTransform
	18, // 25: route.v1.ClientAuthPolicy.secret_ref:type_name -> route.v1.SecretKeyReference
	25, // 26: route.v1.AgentRateLimitPolicy.window:type_name -> google.protobuf.Duration
	2,  // 27: route.v1.AgentRateLimitPolicy.key:type_name -> route.v1.AgentRateLimitKey
	25, // 28: route.v1.AgentTokenLimitPolicy.window:type_name -> google.protobuf.Duration
	2,  // 29: route.v1.AgentTokenLimitPolicy.key:type_name -> route.v1.AgentRateLimitKey
	23, // 30: route.v1.AgentHeaderTransform.add:type_name -> route.v1.AgentHeaderValue
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_route_v1_agent_config_proto_init() }
func file_route_v1_agent_config_proto_init() {
	if File_route_v1_agent_config_proto != nil {
		return
	}
	file_route_v1_agent_config_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentBackend_Http)(nil),
		(*AgentBackend_Llm)(nil),
		(*AgentBackend_Mcp)(nil),
		(*AgentBackend_A2A)(nil),
	}
	file_route_v1_agent_config_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentPathMatch_Prefix)(nil),
		(*AgentPathMatch_Exact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_v1_agent_config_proto_rawDesc), len(file_route_v1_agent_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_route_v1_agent_config_proto_goTypes,
		DependencyIndexes: file_route_v1_agent_config_proto_depIdxs,
		EnumInfos:         file_route_v1_agent_config_proto_enumTypes,
		MessageInfos:      file_route_v1_agent_config_proto_msgTypes,
	}.Build()
	File_route_v1_agent_config_proto = out.File
	file_route_v1_agent_config_proto_goTypes = nil
	file_route_v1_agent_config_proto_depIdxs = nil
}
